import { cleanup, fireEvent, screen, waitFor } from '@testing-library/react-native';
import { onlineManager } from '@tanstack/react-query';
import * as SecureStore from 'expo-secure-store';
import { router } from 'expo-router';
import { renderWithProviders } from '@/test/render';
import { setApiKey } from '@/lib/api-session';
import { CheckoutsScreen } from '../screens/CheckoutsScreen';
import { CommerceCheckoutDetailsScreen, InvalidCheckoutScreen } from '../screens/CheckoutDetailsScreen';
import { checkout, checkoutId, checkoutListItem, page, response } from '../test-fixtures';

jest.mock('expo-router', () => ({ router: { replace: jest.fn(), push: jest.fn() } }));
const fetchMock = jest.spyOn(globalThis, 'fetch');
beforeEach(() => { setApiKey('test-key'); jest.mocked(SecureStore.getItemAsync).mockResolvedValue('test-key'); fetchMock.mockReset(); jest.mocked(router.push).mockClear(); jest.mocked(router.replace).mockClear(); });
afterEach(async () => { await cleanup(); onlineManager.setOnline(true); setApiKey(null); });

test('renders shared cards and pagination, debounces search, and resets pages with filters', async () => {
  fetchMock.mockImplementation(async url => { const n = Number(new URL(String(url)).searchParams.get('pageNumber')); return response(page([{ ...checkoutListItem, name: n ? 'Second checkout' : checkout.name }], n, !n)); });
  await renderWithProviders(<CheckoutsScreen />);
  await screen.findByRole('button', { name: `View checkout: ${checkout.name}` });
  expect(screen.getByText('Event: Community night')).toBeOnTheScreen(); expect(screen.getByText('Form: Guest information')).toBeOnTheScreen();
  expect(screen.getByText('1 product')).toBeOnTheScreen();
  await fireEvent.press(screen.getByRole('button', { name: 'Next' }));
  await screen.findByRole('button', { name: 'View checkout: Second checkout' });
  await fireEvent.press(screen.getByRole('button', { name: 'Filters' }));
  await fireEvent.press(screen.getByRole('radio', { name: 'Primary filter: Closed' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Apply filters' }));
  await screen.findByRole('button', { name: `View checkout: ${checkout.name}` });
  expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('pageNumber')).toBe('0');
  await fireEvent.changeText(screen.getByLabelText('Search'), 'A & B');
  expect(screen.queryByRole('button', { name: `View checkout: ${checkout.name}` })).toBeNull();
  await waitFor(() => expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('search')).toBe('A & B'));
  await fireEvent.press(screen.getByRole('button', { name: 'Sort: Created date' }));
  await fireEvent.press(screen.getByRole('radio', { name: 'Sort by Product count' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Apply sort' }));
  await waitFor(() => expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('sortField')).toBe('productsCount'));
});
test('event picker searches and paginates, stages selection, and retains its display name', async () => {
  fetchMock.mockImplementation(async value => {
    const url = new URL(String(value));
    if (url.pathname.includes('/events/')) return response({ data: [{ id: 'event-1', name: url.searchParams.get('page') === '1' ? 'Next event' : 'Community night' }], hasMore: url.searchParams.get('page') === '0' });
    return response(page([checkoutListItem]));
  });
  await renderWithProviders(<CheckoutsScreen />);
  await screen.findByRole('button', { name: `View checkout: ${checkout.name}` });
  await fireEvent.press(screen.getByRole('button', { name: 'Filters' }));
  expect(fetchMock.mock.calls.some(([url]) => String(url).includes('/events/'))).toBe(false);
  await fireEvent.press(screen.getByRole('button', { name: 'Choose event' }));
  await screen.findByRole('radio', { name: 'Select event Community night' });
  await fireEvent.press(screen.getByRole('button', { name: 'Next events' }));
  await screen.findByRole('radio', { name: 'Select event Next event' });
  await fireEvent.changeText(screen.getByLabelText('Search events'), 'Community');
  await waitFor(() => expect(fetchMock.mock.calls.some(([value]) => { const url = new URL(String(value)); return url.pathname.includes('/events/') && url.searchParams.get('search') === 'Community' && url.searchParams.get('page') === '0'; })).toBe(true));
  await fireEvent.press(await screen.findByRole('radio', { name: 'Select event Community night' }));
  await fireEvent.changeText(screen.getByLabelText('Timeslot ID'), 'slot-1');
  expect(fetchMock.mock.calls.filter(([url]) => String(url).includes('/checkouts/'))).toHaveLength(1);
  await fireEvent.press(screen.getByRole('button', { name: 'Apply filters' }));
  await waitFor(() => expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('eventId')).toBe('event-1'));
  expect(screen.getByRole('button', { name: 'Remove community night filter' })).toBeOnTheScreen();
  expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('timeslotId')).toBe('slot-1');
  await fireEvent.press(screen.getByRole('button', { name: 'Filters (2)' }));
  expect(screen.getByRole('button', { name: 'Choose event' })).toHaveTextContent(/Community night/);
  await fireEvent.press(screen.getByRole('button', { name: 'Close options' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Remove community night filter' }));
  await waitFor(() => expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.has('eventId')).toBe(false));
});
test('cancel discards filter drafts and reset clears applied filters', async () => {
  fetchMock.mockResolvedValue(response(page([])));
  await renderWithProviders(<CheckoutsScreen />); await screen.findByText('No checkouts found');
  await fireEvent.press(screen.getByRole('button', { name: 'Filters' }));
  await fireEvent.changeText(screen.getByLabelText('Timeslot ID'), 'discard');
  await fireEvent.press(screen.getByRole('button', { name: 'Close options' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Filters' }));
  expect(screen.getByLabelText('Timeslot ID')).toHaveDisplayValue('');
  await fireEvent.changeText(screen.getByLabelText('Timeslot ID'), 'saved');
  await fireEvent.press(screen.getByRole('button', { name: 'Apply filters' }));
  await screen.findByRole('button', { name: 'Remove timeslot filter' });
  await fireEvent.press(screen.getByRole('button', { name: 'Filters (1)' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Reset' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Apply filters' }));
  expect(screen.queryByRole('button', { name: 'Remove timeslot filter' })).toBeNull();
});
test('visual conditions validate before applying and serialize nested groups', async () => {
  fetchMock.mockResolvedValue(response(page([])));
  await renderWithProviders(<CheckoutsScreen />); await screen.findByText('No checkouts found');
  await fireEvent.press(screen.getByRole('button', { name: 'Filters' }));
  await fireEvent.press(screen.getByRole('button', { name: 'Add filter group' }));
  expect(screen.getByRole('button', { name: 'Apply filters' })).toBeDisabled();
  await fireEvent.changeText(screen.getByLabelText('Group 1 1 value'), 'pass');
  await fireEvent.press(screen.getByRole('button', { name: 'Add subgroup to group 1' }));
  await fireEvent.changeText(screen.getByLabelText('Group 1 2 1 value'), 'evening');
  await fireEvent.press(screen.getByRole('button', { name: 'Apply filters' }));
  await waitFor(() => expect(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.has('filters')).toBe(true));
  expect(JSON.parse(new URL(String(fetchMock.mock.calls.at(-1)?.[0])).searchParams.get('filters') ?? '')).toEqual([{ logic: 'and', conditions: [{ field: 'name', operator: 'contains', value: 'pass' }, { logic: 'and', conditions: [{ field: 'name', operator: 'contains', value: 'evening' }] }] }]);
});
test('recovers from a permission error, supports empty lists and honest offline states', async () => {
  fetchMock.mockResolvedValueOnce(response({}, 403));
  await renderWithProviders(<CheckoutsScreen />); await screen.findByText('You do not have permission to perform this action.');
  fetchMock.mockResolvedValueOnce(response(page([])));
  await fireEvent.press(screen.getByRole('button', { name: 'Try again' })); await screen.findByText('No checkouts found');
  await cleanup(); fetchMock.mockClear(); onlineManager.setOnline(false);
  await renderWithProviders(<CheckoutsScreen />); await screen.findByText('You are offline. Connect to load data.');
  expect(fetchMock).not.toHaveBeenCalled();
});
test('details render nested settings and preserve zero and false values', async () => {
  fetchMock.mockResolvedValue(response({ checkout }));
  await renderWithProviders(<CommerceCheckoutDetailsScreen checkoutId={checkoutId} />);
  await screen.findByRole('header', { name: checkout.name });
  await fireEvent.press(screen.getByRole('button', { name: 'Payment settings' }));
  expect(screen.getByText('Card, Pay by invoice')).toBeOnTheScreen(); expect(screen.getByText('test-tax-id')).toBeOnTheScreen();
  await fireEvent.press(screen.getByRole('button', { name: 'Product 1: product-1' }));
  expect(screen.getByText('0')).toBeOnTheScreen();
  await fireEvent.press(screen.getByRole('button', { name: 'Dependent product 1' }));
  expect(screen.getByText('250')).toBeOnTheScreen(); expect(screen.getByText('Currency and price units are not provided.')).toBeOnTheScreen();
  expect(screen.getByText('Handling')).toBeOnTheScreen(); expect(screen.getAllByText('No').length).toBeGreaterThan(0);
});
test('details handle missing fields, empty products, refresh failures and return navigation', async () => {
  const minimal = { id: checkoutId, ownerId: 'workspace', name: 'Minimal', status: 'closed', visibility: 'private', products: [], createdAt: checkout.createdAt, updatedAt: checkout.updatedAt };
  fetchMock.mockResolvedValueOnce(response({ checkout: minimal }));
  await renderWithProviders(<CommerceCheckoutDetailsScreen checkoutId={checkoutId} />);
  await screen.findByText('No products configured');
  expect(screen.getAllByText('Not provided').length).toBeGreaterThan(0);
  fetchMock.mockResolvedValueOnce(response({}, 403));
  await fireEvent.press(screen.getByRole('button', { name: 'Refresh checkout' }));
  await screen.findByText('Showing previously loaded data.');
  expect(screen.getByRole('header', { name: 'Minimal' })).toBeOnTheScreen();
  await fireEvent.press(screen.getByRole('button', { name: 'Back to Checkouts' })); expect(router.replace).toHaveBeenCalledWith('/commerce/checkouts');
});
test('invalid links never fetch and unavailable checkouts show a safe error', async () => {
  await renderWithProviders(<InvalidCheckoutScreen />);
  expect(screen.getByText('This checkout link is invalid.')).toBeOnTheScreen(); expect(fetchMock).not.toHaveBeenCalled();
  await cleanup(); setApiKey('test-key'); fetchMock.mockResolvedValue(response({}, 404));
  await renderWithProviders(<CommerceCheckoutDetailsScreen checkoutId={checkoutId} />);
  await screen.findByText('This checkout could not be found or is no longer available.');
});
